//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fitshop.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class fitshopEntities : DbContext
    {
        public fitshopEntities()
            : base("name=fitshopEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<food> food { get; set; }
        public virtual DbSet<roles> roles { get; set; }
        public virtual DbSet<token> token { get; set; }
        public virtual DbSet<user> user { get; set; }
        public virtual DbSet<userRoles> userRoles { get; set; }
    }
}
