//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fitshop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class token
    {
        public int id { get; set; }
        public int userId { get; set; }
        public string tokenValue { get; set; }
        public System.DateTime expire { get; set; }
        public bool active { get; set; }
    
        public virtual user user { get; set; }
    }
}
