//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fitshop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class userRoles
    {
        public int id { get; set; }
        public int userId { get; set; }
        public int rolesId { get; set; }
    
        public virtual roles roles { get; set; }
        public virtual user user { get; set; }
    }
}
